In [1]:
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, classification_report, f1_score, recall_score
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from imblearn.under_sampling import RandomUnderSampler
from sklearn.metrics import classification_report, confusion_matrix, classification_report, f1_score, recall_score
from sklearn.cluster import KMeans
from joblib import dump, load


In [2]:
data = pd.read_csv('Data/25day_dataset.csv')

label = []
for i in range(len(data)):
    if data['wahing_machine'].iloc[i]==0 and data['dishwasher'].iloc[i]==0 and data['oven'].iloc[i]==0:
        label.append(0)
    elif data['wahing_machine'].iloc[i]>0:
        label.append(1)
    elif data['dishwasher'].iloc[i]>0:
        label.append(2)
    elif data['oven'].iloc[i]>0:
        label.append(3)
data['Class'] = label

In [3]:
Test_set1 =data[data['DateTime'].str.startswith('2022-01-01')]
Test_set2 =data[data['DateTime'].str.startswith('2022-01-02')]
Test_set3 =data[data['DateTime'].str.startswith('2022-01-03')]
Test_set4 =data[data['DateTime'].str.startswith('2022-01-04')]
Test_set5 =data[data['DateTime'].str.startswith('2022-01-05')]
Test_set6 =data[data['DateTime'].str.startswith('2022-01-06')]
Test_set7 =data[data['DateTime'].str.startswith('2022-01-07')]
Test_set8 =data[(data['DateTime'].str.startswith('2022-01-08'))]
Test_set9 =data[(data['DateTime'].str.startswith('2022-01-10')) | (data['DateTime'].str.startswith('2022-01-11'))]
Test_set10 =data[(data['DateTime'].str.startswith('2022-01-12')) | (data['DateTime'].str.startswith('2022-01-13'))]
test_set_list= [Test_set1, Test_set2, Test_set3, Test_set4, Test_set5, Test_set6, Test_set7, Test_set8, Test_set9, Test_set10]

In [5]:
f_score={}
recall={}

#Ciclo per scorrere le fold di test e trainare un modello per ognuna di esse
for i in range(len(test_set_list)):
    
    clf = load(f'Models_Ensemble/ensemble{i}.sav')
    
    X_test = test_set_list[i].copy().drop(['DateTime', 'Class', 'wahing_machine', 'dishwasher', 'oven'], axis=1)
    y_test = test_set_list[i].Class
    
    y_preds = clf.predict(X_test)
    
    print("CM:\n" + str(confusion_matrix(y_test,y_preds)) + "\n")
    print(classification_report(y_test,y_preds))
    
    r = recall_score(y_test,y_preds, average= None) 
    f = f1_score(y_test,y_preds, average= None)
    f_score[i] = f
    recall[i] = r 
 
#Calcola medie 
f1= pd.DataFrame.from_dict(f_score, orient='index').replace(0, np.nan)
print(f1.mean(axis=0, skipna=True))
r1= pd.DataFrame.from_dict(recall, orient='index').replace(0, np.nan)
print(r1.mean(axis=0, skipna=True))

CM:
[[80216   356   909   184]
 [  106  3946     0     1]
 [    0     0     0     0]
 [   92     0     0   590]]

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     81665
           1       0.92      0.97      0.94      4053
           2       0.00      0.00      0.00         0
           3       0.76      0.87      0.81       682

    accuracy                           0.98     86400
   macro avg       0.67      0.71      0.69     86400
weighted avg       0.99      0.98      0.99     86400



C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarni

CM:
[[76163   810   593   703]
 [  640  6354     0    14]
 [    0     0     0     0]
 [   55     0     0  1068]]

              precision    recall  f1-score   support

           0       0.99      0.97      0.98     78269
           1       0.89      0.91      0.90      7008
           2       0.00      0.00      0.00         0
           3       0.60      0.95      0.73      1123

    accuracy                           0.97     86400
   macro avg       0.62      0.71      0.65     86400
weighted avg       0.98      0.97      0.97     86400



C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarni

CM:
[[79310   263   103  1419]
 [  161   817     0    46]
 [  545   122  2910     0]
 [    0     0     0   704]]

              precision    recall  f1-score   support

           0       0.99      0.98      0.98     81095
           1       0.68      0.80      0.73      1024
           2       0.97      0.81      0.88      3577
           3       0.32      1.00      0.49       704

    accuracy                           0.97     86400
   macro avg       0.74      0.90      0.77     86400
weighted avg       0.98      0.97      0.97     86400

CM:
[[81594    81     0    80]
 [    0     0     0     0]
 [    0     0     0     0]
 [  890   865     4  2886]]

              precision    recall  f1-score   support

           0       0.99      1.00      0.99     81755
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.97      0.62      0.76      4645

    accuracy                           0.98     86400
   macro av

C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarni

CM:
[[82378   333    16     8]
 [  255  3400     0    10]
 [    0     0     0     0]
 [    0     0     0     0]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     82735
           1       0.91      0.93      0.92      3665
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

    accuracy                           0.99     86400
   macro avg       0.48      0.48      0.48     86400
weighted avg       0.99      0.99      0.99     86400



C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarni

CM:
[[81340   596   370   116]
 [    0     0     0     0]
 [  300   323  3349     6]
 [    0     0     0     0]]

              precision    recall  f1-score   support

           0       1.00      0.99      0.99     82422
           1       0.00      0.00      0.00         0
           2       0.90      0.84      0.87      3978
           3       0.00      0.00      0.00         0

    accuracy                           0.98     86400
   macro avg       0.47      0.46      0.47     86400
weighted avg       0.99      0.98      0.99     86400



C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarni

CM:
[[79484   454   162   856]
 [  244  3013     0     1]
 [    0     0     0     0]
 [  489     2     2  1693]]

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     80956
           1       0.87      0.92      0.90      3258
           2       0.00      0.00      0.00         0
           3       0.66      0.77      0.71      2186

    accuracy                           0.97     86400
   macro avg       0.63      0.67      0.65     86400
weighted avg       0.98      0.97      0.98     86400



C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarni

CM:
[[79560   305  1150   424]
 [  171  3984     0     0]
 [    0     0     0     0]
 [  330     0     0   476]]

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     81439
           1       0.93      0.96      0.94      4155
           2       0.00      0.00      0.00         0
           3       0.53      0.59      0.56       806

    accuracy                           0.97     86400
   macro avg       0.61      0.63      0.62     86400
weighted avg       0.99      0.97      0.98     86400



C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarni

CM:
[[166899    328    327    677]
 [   145   2637      0      8]
 [     0      0      0      0]
 [   634      0      0   1145]]

              precision    recall  f1-score   support

           0       1.00      0.99      0.99    168231
           1       0.89      0.95      0.92      2790
           2       0.00      0.00      0.00         0
           3       0.63      0.64      0.63      1779

    accuracy                           0.99    172800
   macro avg       0.63      0.65      0.64    172800
weighted avg       0.99      0.99      0.99    172800



C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarni

CM:
[[157833    649    373   1067]
 [   533   5953      0      4]
 [   712      0   2750      1]
 [    69      1      1   2854]]

              precision    recall  f1-score   support

           0       0.99      0.99      0.99    159922
           1       0.90      0.92      0.91      6490
           2       0.88      0.79      0.83      3463
           3       0.73      0.98      0.83      2925

    accuracy                           0.98    172800
   macro avg       0.88      0.92      0.89    172800
weighted avg       0.98      0.98      0.98    172800

0    0.989243
1    0.894961
2    0.862781
3    0.691692
dtype: float64
0    0.985169
1    0.918986
2    0.816507
3    0.802729
dtype: float64
