In [92]:
from numpy import mean
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from imblearn.ensemble import EasyEnsembleClassifier

data = pd.read_csv('Data/25day_dataset.csv')

In [ ]:
label = []
for i in range(len(data)):
    if data['wahing_machine'].iloc[i]==0 and data['dishwasher'].iloc[i]==0 and data['oven'].iloc[i]==0:
        label.append(0)
    elif data['wahing_machine'].iloc[i]>0:
        label.append(1)
    elif data['dishwasher'].iloc[i]>0:
        label.append(2)
    elif data['oven'].iloc[i]>0:
        label.append(3)
data['Class'] = label

In [ ]:
Test_set1 =data[data['DateTime'].str.startswith('2022-01-01')]
Test_set2 =data[data['DateTime'].str.startswith('2022-01-02')]
Test_set3 =data[data['DateTime'].str.startswith('2022-01-03')]
Test_set4 =data[data['DateTime'].str.startswith('2022-01-04')]
Test_set5 =data[data['DateTime'].str.startswith('2022-01-05')]
Test_set6 =data[data['DateTime'].str.startswith('2022-01-06')]
Test_set7 =data[data['DateTime'].str.startswith('2022-01-07')]
Test_set8 =data[(data['DateTime'].str.startswith('2022-01-08')) | (data['DateTime'].str.startswith('2022-01-09'))]
Test_set9 =data[(data['DateTime'].str.startswith('2022-01-10')) | (data['DateTime'].str.startswith('2022-01-11'))]
Test_set10 =data[(data['DateTime'].str.startswith('2022-01-12')) | (data['DateTime'].str.startswith('2022-01-13'))]
test_set_list= [Test_set1, Test_set2, Test_set3, Test_set4, Test_set5, Test_set6, Test_set7, Test_set8, Test_set9, Test_set10]

In [6]:
for i in range(0,9):
    data.drop(test_set_list[i].index, axis=0, inplace=True)
X = data.drop(['DateTime', 'Class', 'wahing_machine', 'dishwasher', 'oven'], axis=1)
y = data['Class']


ActivePower  ReactivePower   Voltage   Current  harmonic1_Real  \
950400      0.033832       0.093537  0.000165  0.000440       -0.000069   
950401      0.034252       0.094019  0.000165  0.000446       -0.000069   
950402      0.033736       0.096428  0.000165  0.000440       -0.000071   
950403      0.034199       0.091883  0.000165  0.000444       -0.000068   
950404      0.033841       0.093186  0.000165  0.000440       -0.000069   
...              ...            ...       ...       ...             ...   
2159995     0.016614       0.049226  0.000163  0.000217        0.000021   
2159996     0.016512       0.050061  0.000163  0.000216        0.000021   
2159997     0.016713       0.048425  0.000163  0.000219        0.000020   
2159998     0.016617       0.049573  0.000163  0.000217        0.000020   
2159999     0.016823       0.048671  0.000163  0.000220        0.000021   

         harmonic1_Imaginary  harmonic3_Real  harmonic3_Imaginary  \
950400             -0.000475        0.000017            -0.000035   
950401             -0.000486        0.000017            -0.000039   
950402             -0.000472        0.000015            -0.000035   
950403             -0.000483        0.000018            -0.000039   
950404             -0.000473        0.000018            -0.000035   
...                      ...             ...                  ...   
2159995            -0.000233        0.000011            -0.000045   
2159996            -0.000232        0.000011            -0.000044   
2159997            -0.000236        0.000011            -0.000046   
2159998            -0.000231        0.000011            -0.000044   
2159999            -0.000234        0.000011            -0.000046   

         harmonic5_Real  harmonic5_Imaginary  harmonic7_Real  \
950400        -0.000007            -0.000012    0.000000e+00   
950401        -0.000007            -0.000013   -2.803726e-06   
950402        -0.000009            -0.000011   -7.710246e-06   
950403        -0.000008            -0.000013    0.000000e+00   
950404        -0.000008            -0.000012   -5.607452e-06   
...                 ...                  ...             ...   
2159995       -0.000011            -0.000018   -6.308383e-06   
2159996       -0.000011            -0.000018   -2.803726e-06   
2159997       -0.000011            -0.000019   -7.009315e-07   
2159998       -0.000011            -0.000018   -1.401863e-06   
2159999       -0.000011            -0.000019   -7.009315e-07   

         harmonic7_Imaginary  
950400             -0.000002  
950401             -0.000001  
950402             -0.000004  
950403             -0.000007  
950404             -0.000001  
...                      ...  
2159995            -0.000007  
2159996            -0.000006  
2159997            -0.000009  
2159998            -0.000008  
2159999            -0.000009  

[1209600 rows x 12 columns]

In [8]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=25, n_estimators=15)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
scores

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan])

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from imblearn.under_sampling import RandomUnderSampler
from sklearn.metrics import classification_report, confusion_matrix, classification_report, f1_score, recall_score

param_grid = {
    'max_depth': [5,10,15,20],
    'criterion' :['gini','entropy'],
    'n_estimators': [5,10,20,30], 
    'max_features': ['sqrt', 'log2', None]
}
# Create a base model
clf = RandomForestClassifier()

one= int((y.values == 1).sum()*0.5) 
two= int((y.values == 2).sum())
three= int((y.values == 3).sum())
#Fai undersample sulle x e y di train
n= 130000 - one - two - three
undersample = RandomUnderSampler(sampling_strategy={0: n, 1: one, 2: two, 3: three})
X_new, y_new = undersample.fit_resample(X, y)

# Instantiate the grid search model
clf = GridSearchCV(estimator = clf, cv=5,param_grid = param_grid, verbose = 2, return_train_score=True)
# Fit the grid search to the data
clf.fit(X_new, y_new)



Fitting 5 folds for each of 96 candidates, totalling 480 fits
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=5; total time=   0.2s
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=5; total time=   0.3s
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=5; total time=   0.2s
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=5; total time=   0.3s
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=5; total time=   0.2s
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=10; total time=   0.5s
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=10; total time=   0.5s
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=10; total time=   0.5s
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=10; total time=   0.5s
[CV] END criterion=gini, max_depth=5, max_features=sqrt, n_estimators=10; total time=   0.5s
[CV] END crit

[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=10; total time=   1.1s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=10; total time=   1.2s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=20; total time=   2.1s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=20; total time=   2.4s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=20; total time=   2.6s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=20; total time=   2.3s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=20; total time=   2.3s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=30; total time=   3.5s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=30; total time=   3.9s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_estimators=30; total time=   3.6s
[CV] END criterion=gini, max_depth=10, max_features=log2, n_

[CV] END criterion=gini, max_depth=15, max_features=None, n_estimators=30; total time=  17.4s
[CV] END criterion=gini, max_depth=15, max_features=None, n_estimators=30; total time=  16.7s
[CV] END criterion=gini, max_depth=15, max_features=None, n_estimators=30; total time=  18.3s
[CV] END criterion=gini, max_depth=15, max_features=None, n_estimators=30; total time=  17.9s
[CV] END criterion=gini, max_depth=20, max_features=sqrt, n_estimators=5; total time=   0.9s
[CV] END criterion=gini, max_depth=20, max_features=sqrt, n_estimators=5; total time=   0.9s
[CV] END criterion=gini, max_depth=20, max_features=sqrt, n_estimators=5; total time=   1.0s
[CV] END criterion=gini, max_depth=20, max_features=sqrt, n_estimators=5; total time=   0.9s
[CV] END criterion=gini, max_depth=20, max_features=sqrt, n_estimators=5; total time=   0.8s
[CV] END criterion=gini, max_depth=20, max_features=sqrt, n_estimators=10; total time=   1.6s
[CV] END criterion=gini, max_depth=20, max_features=sqrt, n_estim

[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=5; total time=   0.3s
[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=5; total time=   0.4s
[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=10; total time=   0.7s
[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=10; total time=   0.7s
[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=10; total time=   0.6s
[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=10; total time=   0.9s
[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=10; total time=   0.9s
[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=20; total time=   1.9s
[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=20; total time=   1.6s
[CV] END criterion=entropy, max_depth=5, max_features=log2, n_estimators=20; total time=   1.7s
[CV] END criterion=entropy, max_depth=5, m

[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=10; total time=   6.1s
[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=20; total time=   9.8s
[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=20; total time=  10.3s
[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=20; total time=   9.8s
[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=20; total time=   9.6s
[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=20; total time=  10.2s
[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=30; total time=  14.9s
[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=30; total time=  15.1s
[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=30; total time=  15.3s
[CV] END criterion=entropy, max_depth=10, max_features=None, n_estimators=30; total time=  15.7s
[CV] END criterion=entropy, ma

[CV] END criterion=entropy, max_depth=20, max_features=sqrt, n_estimators=20; total time=   3.9s
[CV] END criterion=entropy, max_depth=20, max_features=sqrt, n_estimators=30; total time=   5.3s
[CV] END criterion=entropy, max_depth=20, max_features=sqrt, n_estimators=30; total time=   5.7s
[CV] END criterion=entropy, max_depth=20, max_features=sqrt, n_estimators=30; total time=   5.7s
[CV] END criterion=entropy, max_depth=20, max_features=sqrt, n_estimators=30; total time=   5.2s
[CV] END criterion=entropy, max_depth=20, max_features=sqrt, n_estimators=30; total time=   6.1s
[CV] END criterion=entropy, max_depth=20, max_features=log2, n_estimators=5; total time=   1.0s
[CV] END criterion=entropy, max_depth=20, max_features=log2, n_estimators=5; total time=   0.8s
[CV] END criterion=entropy, max_depth=20, max_features=log2, n_estimators=5; total time=   0.8s
[CV] END criterion=entropy, max_depth=20, max_features=log2, n_estimators=5; total time=   0.9s
[CV] END criterion=entropy, max_de

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 10, 15, 20],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [5, 10, 20, 30]},
             return_train_score=True, verbose=2)

In [24]:
clf.best_params_

{'criterion': 'entropy',
 'max_depth': 20,
 'max_features': 'log2',
 'n_estimators': 30}

In [89]:
import numpy as np
model= RandomForestClassifier(criterion= 'entropy',
 max_depth= 20,
 max_features= 'log2',
 n_estimators= 30)

model.fit(X_new,y_new)
misclassified = []
for i in range(0,10):
    
    Test_set= test_set_list[i]
    y_preds= model.predict(Test_set.drop(['DateTime', 'Class', 'wahing_machine', 'dishwasher', 'oven'], axis=1))
    y_test = np.asarray(y_new)
    err= np.where(y_test != y_preds)
    misclassified.append(err)
    #Stampa le statistiche per la fold e memorizza le metriche di f1score e recall
    #print("CM:\n" + str(confusion_matrix(Test_set.Class,y_preds)) + "\n")
    #print(classification_report(Test_set.Class,y_preds))

C:\Users\massi\AppData\Local\Temp\ipykernel_13980\3611498095.py:14: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  err= np.where(y_test != y_preds)
C:\Users\massi\AppData\Local\Temp\ipykernel_13980\3611498095.py:14: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  err= np.where(y_test != y_preds)
C:\Users\massi\AppData\Local\Temp\ipykernel_13980\3611498095.py:14: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  err= np.where(y_test != y_preds)
C:\Users\massi\AppData\Local\Temp\ipykernel_13980\3611498095.py:14: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  err= np.where(y_test != y_preds)
C:\Users\massi\AppData\Local\Temp\ipykernel_13980\3611498095.py:14: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  err= np.where(y_test != y_preds)
C:\Users\massi\AppData\Local\T

In [90]:
misclassified

[(array([0], dtype=int64),),
 (array([0], dtype=int64),),
 (array([0], dtype=int64),),
 (array([0], dtype=int64),),
 (array([0], dtype=int64),),
 (array([0], dtype=int64),),
 (array([0], dtype=int64),),
 (array([0], dtype=int64),),
 (array([0], dtype=int64),)]